[package]
name = "tagged_union_derive"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]

[dependencies]
syn = "0.11.11"
quote = "0.3.15"

[lib]
name = "tagged_union_derive"
proc_macro = true